global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "zookeeper"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["zk1:7000", "zk2:7000", "zk3:7000"]

  - job_name: "backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["zk-demo-backend:8080"]
