global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "zookeeper"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["zk-exporter-1:8080", "zk-exporter-2:8080", "zk-exporter-3:8080"]

  - job_name: "backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["zk-demo-backend:8080"]
